### ISSUE TITLE
Pin libprotobuf?

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/libignition-msgs1-feedstock#18]
We're running into problems as downstream packages (in this case, https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/14) complain that the msgs from the libignition-msgs package are built using a newer version of libprotobuf. Should we pin down libprotobuf so this doesn't happen in the future?

**Comment by traversaro** [comment]
As far as I can see in the `info/recipe/meta.yaml` file in the `6.1.0_1`  there is the correct pin, that was added there by `run_exports` of `libprotobuf`:
~~~
        - libprotobuf >=3.14.0,<3.15.0a0
~~~
The problem that was that in https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/14 probably ignition-msgs6 `6.1.0_0`  build only had as run dependency:
~~~
        - protobuf
~~~
and that was probably an missing run_export in protobuf, that is however solved now, so I guess that no further action is required on this feedstock.

**Comment by Tobias-Fischer** [comment]
Great that's good to know, thanks @traversaro
