### ISSUE TITLE
Error in autotick bot

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-msgs1-feedstock#50]
We noticed here and in other ignition packages that the autotick bot to open PR for new version was not working correctly. Thanks to a message in conda-forge chat, I discovered that there is a specific section in conda-forge status page to report this errors, https://conda-forge.org/status/#version_updates (thanks a lot to @beckermr for that).

In that, I found that the error related to ignition-msgs1 is:
~~~
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '7_7.1.0' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://github.com/ignitionrobotics/ign-msgs/archive/ignition-msgs{{ version.split('.')[0] }}_{{ version }}.tar.gz'
~~~

While the error could be related to the  jinja2 syntax in the url template, that worked fine in the past, see for example https://github.com/conda-forge/libignition-msgs1-feedstock/pull/32 . I wonder if the actual problem is that the bot thinks that the new version is `7_7.1.0` instead of `7.1.0`, and this is creating problems. @wolfv @Tobias-Fischer any idea?

**Comment by traversaro** [comment]
As the migrator was working in https://github.com/conda-forge/libignition-msgs1-feedstock/pull/32, I wonder if https://github.com/regro/cf-scripts/pull/1391 or https://github.com/regro/cf-scripts/pull/1398 are related changes.

**Comment by wolfv** [comment]
i just had a quick look at the code and I don't know what's going on, unfortunately.

**Comment by wolfv** [comment]
what i checked:

- filename on github release seems to be correct
- what the code does is to download the release `.tar.gz` file, and then compute the SHA256 sum
- maybe there is a timeout that's hit (one of the conditions for it to return None)

Idk if it already re-ran a couple of times -- it might fix itself. Otherwise maybe running this thing locally could give more clues :)

**Comment by beckermr** [comment]
The bot is not getting the upstream version correctly due to its weird format.

```
Please check the URLs in your recipe with version '7_7.1.0' to make sure they exist!
```

**Comment by traversaro** [comment]
> 
> 
> The bot is not getting the upstream version correctly due to its weird format.
> 
> ```
> Please check the URLs in your recipe with version '7_7.1.0' to make sure they exist!
> ```
 
Thanks! I supposed this, but I was not so certain as in the past it seems it was working fine, see for example https://github.com/conda-forge/libignition-msgs1-feedstock/pull/32 . There is any solution we can have beside upstream switching to a tag scheme that is not prefixed by `igniton-msgs<major_version>_`?

**Comment by beckermr** [comment]
see this: https://github.com/conda-forge/libignition-msgs1-feedstock/pull/51

**Comment by beckermr** [comment]
The regex here anyways takes the first digit: https://github.com/regro/cf-scripts/blob/4a900e9eb3a6560a877825e2074c22502644c3ee/conda_forge_tick/update_sources.py#L153

**Comment by beckermr** [comment]
not sure how or why it worked in the past - might be related to the major version bump triggering a different code path

**Comment by traversaro** [comment]
`libignition-msgs` is not anymore listed in https://conda-forge.org/status/#version_updates among the ports with version-related errors, thanks againg @beckermr .

**Comment by traversaro** [comment]
Just cross-linking an issue that seems to occur with the fix discussed in this issue: https://github.com/conda-forge/libignition-msgs1-feedstock/issues/53 .
