### ISSUE TITLE
Problem in autotick-bot not creating PRs 

### ISSUE THREAD

**Issue by traversaro** [conda-forge/libignition-msgs1-feedstock#53]
(Note: this problem probably applies to all ignition conda-forge packages, but I opened it here as here we already managed https://github.com/conda-forge/libignition-msgs1-feedstock/issues/50). 

It seems that the fix proposed in https://github.com/conda-forge/libignition-msgs1-feedstock/issues/50 works fine in making sure that no version-related error for the ignition packages appear in https://conda-forge.org/status/#version_updates . However, it seems that there are a few packages that saw new version releases, but no autotick PRs. In particular, if you look at the output of the versions CI job (see https://github.com/regro/autotick-bot/runs/3200657715):
~~~
2021-07-30T09:48:18.1896351Z 2021-07-30 09:48:18,189 INFO     conda_forge_tick.update_upstream_versions || itr  11745 - eta   484s: libignition-gui - 5.1.0 - 5.2.0
[..]
2021-07-30T10:00:36.9221838Z 2021-07-30 10:00:36,921 INFO     conda_forge_tick.update_upstream_versions || itr  6135 - eta   685s: libignition-physics - 4.1.0 - 4.2.0
~~~

Indeed, it seems that upstream tags were done (see for example https://github.com/ignitionrobotics/ign-physics/releases/tag/ignition-physics4_4.2.0 and https://github.com/conda-forge/libignition-physics-feedstock) and , but no PR is being generated for some reason.

**Comment by beckermr** [comment]
ugh not again. Now the bot is finding the actual version string and not the one with the extra number. I will check into this.

**Comment by beckermr** [comment]
I think I pushed a fix to the bot that will handle this. It will take several hours to propagate. 🤞

**Comment by beckermr** [comment]
huzzah!

https://github.com/regro/cf-graph-countyfair/blob/master/versions/libignition-physics.json

we got the right version. now to see if the bot issues the PR or if we have to reset the version in the node!

**Comment by beckermr** [comment]
🎉 

https://github.com/conda-forge/libignition-physics-feedstock/pull/20/files

**Comment by Tobias-Fischer** [comment]
Thanks @beckermr :)

**Comment by traversaro** [comment]
Thanks a lot @beckermr ! For future reference, if I am not wrong the fix should be: https://github.com/regro/cf-scripts/pull/1421.

**Comment by beckermr** [comment]
Yep, that's the one! The issue was pretty subtle. Basically, a version update like 4_4.1.0 -> 4_4.2.0 hit one code path but 4_4.2.0 to 5_5.0.0 hit another.
